//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.mayi.julyup.adapter;

import android.content.Context;

public final class Download_List_Adapter_
    extends Download_List_Adapter
{

    private Context context_;

    private Download_List_Adapter_(Context context) {
        context_ = context;
        init_();
    }

    public static Download_List_Adapter_ getInstance_(Context context) {
        return new Download_List_Adapter_(context);
    }

    private void init_() {
        context = context_;
        init();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
