//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.mayi.julyup.adapter;

import android.content.Context;

public final class FaqListAdapter_
    extends FaqListAdapter
{

    private Context context_;

    private FaqListAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static FaqListAdapter_ getInstance_(Context context) {
        return new FaqListAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
