//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.mayi.julyup.adapter;

import android.content.Context;

public final class TASK_ExpandListAdapter_
    extends TASK_ExpandListAdapter
{

    private Context context_;

    private TASK_ExpandListAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static TASK_ExpandListAdapter_ getInstance_(Context context) {
        return new TASK_ExpandListAdapter_(context);
    }

    private void init_() {
        context = context_;
        init();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
