//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.mayi.julyup.adapter;

import android.content.Context;

public final class Upload_Unfinished_list_Adapter_
    extends Upload_Unfinished_list_Adapter
{

    private Context context_;

    private Upload_Unfinished_list_Adapter_(Context context) {
        context_ = context;
        init_();
    }

    public static Upload_Unfinished_list_Adapter_ getInstance_(Context context) {
        return new Upload_Unfinished_list_Adapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
