//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.mayi.julyup.adapter;

import android.content.Context;

public final class UploadFinishListAdapter_
    extends UploadFinishListAdapter
{

    private Context context_;

    private UploadFinishListAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static UploadFinishListAdapter_ getInstance_(Context context) {
        return new UploadFinishListAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
